"""Step 6: print the headline numbers (quoted in README.md) from the result files."""
import json, os
import pandas as pd
from analyze import RES

R = json.load(open(os.path.join(RES, "results.json")))
B = json.load(open(os.path.join(RES, "robustness.json")))
X = json.load(open(os.path.join(RES, "extra_checks.json")))
o1 = pd.read_csv(os.path.join(RES, "orgs_E1_public.csv")).set_index("org")
o2 = pd.read_csv(os.path.join(RES, "orgs_E2_public.csv")).set_index("org")
f = lambda g: f"s={g['s']:.3f} [95% CI {g['ci95'][0]:.3f}, {g['ci95'][1]:.3f}], n={g['repos']}, placebo {g['placebo_mean']:+.3f}±{g['placebo_sd']:.3f}, z={g['z_vs_placebo']:.1f}"
L = ["# Summary of results (auto-generated by src/summarize.py)", ""]
for era in ("E1", "E2"):
    e = R[era]
    L += [f"## {era}: {e['repos_in_panel']} repos in panel, {e['eligible_repos']} eligible, {e['panel_days']} complete days",
          f"- make-up workdays used ({len(e['makeup_events'])}): {', '.join(e['makeup_events'])}",
          f"- China-only holiday weekdays used: {len(e['holiday_events'])}"]
    for k, g in e["groups"].items():
        L.append(f"- {k}: {f(g)}")
    L += [f"- per-repo BH q<0.05 & positive: {e['bh_q05_repos']} (of which <1% Chinese titles: {e['bh_q05_repos_zh_lt_1pct']})",
          f"- holiday-dip mirror estimator by group: " + ", ".join(f"{k}={v:.3f}" for k, v in e["holiday_dip_by_group"].items()), ""]
h = R["holdout_E1_to_E2"]
L += ["## Out-of-sample: flagged in E1 (2023-24) -> measured in E2 (2025-26)", f"- repos in both eras: {h['common_repos']}"]
for k in ("E1 flagged (q<0.05, s>0.3)", "E1 flagged & zh<1%", "E1 not flagged"):
    g = h[k]
    L.append(f"- {k}: n={g['repos']}, E1 s={g['E1_s']:.3f} -> E2 s={g['E2_s']:.3f} [{g['E2_s_ci95'][0]:.3f}, {g['E2_s_ci95'][1]:.3f}]; E2 Spring-Festival-2026 dip={g['E2_holiday_dip']:.3f}")
sh = X["split_half_2023_to_2024"]
L += ["", "## Split-half: flagged on 2023 make-up days -> measured on 2024 make-up days",
      f"- flagged 2023: {sh['flagged_2023']} -> 2024 s={sh['flagged_2023_s_in_2024']:.3f} [{sh['ci95'][0]:.3f}, {sh['ci95'][1]:.3f}]",
      f"- of which <1% Chinese titles: {sh['flagged_2023_zh_lt_1pct']} -> 2024 s={sh['hidden_s_in_2024']:.3f} [{sh['hidden_ci95'][0]:.3f}, {sh['hidden_ci95'][1]:.3f}]",
      f"- not flagged -> 2024 s={sh['not_flagged_s_in_2024']:.3f} [{sh['not_flagged_ci95'][0]:.3f}, {sh['not_flagged_ci95'][1]:.3f}]", ""]
L += ["## Same-time-zone controls (lower-threshold panel, E1)"]
for k, g in B["same_timezone_controls"].items():
    if g["repos"]:
        L.append(f"- {k}: {f(g)}")
pe = B["per_event"]
L += ["", "## Per-event uplift, repos with <1% Chinese titles: " + ", ".join(f"{k}: {v['zh<1%']:.3f}" for k, v in pe.items()),
      f"- positive on {sum(v['zh<1%'] > 0 for v in pe.values())} of {len(pe)} days"]
L += ["", "## Organisations (E1 -> E2)"]
for org in o1.index:
    r1 = o1.loc[org]; s2 = f"{o2.loc[org,'s']:.3f} [{o2.loc[org,'ci95_lo']:.3f}, {o2.loc[org,'ci95_hi']:.3f}] (n={int(o2.loc[org,'repos'])})" if org in o2.index else "n/a"
    L.append(f"- {org}: E1 s={r1.s:.3f} [{r1.ci95_lo:.3f}, {r1.ci95_hi:.3f}] (n={int(r1.repos)}, Chinese-title share {r1.zh_title_share:.4f}); E2 s={s2}")
open(os.path.join(RES, "SUMMARY.md"), "w").write("\n".join(L) + "\n")
print("\n".join(L))
