"""Step 6: print the headline numbers (quoted in README.md / RED_TEAM.md / POST.md) from the result files.
CIs: 'two-way' = pairs bootstrap over repos AND make-up days (primary); 'repo-only' kept for reference."""
import json, os
import pandas as pd
from analyze import RES

R = json.load(open(os.path.join(RES, "results.json")))
B = json.load(open(os.path.join(RES, "robustness.json")))
X = json.load(open(os.path.join(RES, "extra_checks.json")))
H = json.load(open(os.path.join(RES, "mechanism.json")))
C = json.load(open(os.path.join(RES, "capture.json")))
_np = lambda m: sum(v for k, v in C["monthly_events_by_type"][m].items() if k != "PushEvent")
o1 = pd.read_csv(os.path.join(RES, "orgs_E1_public.csv")).set_index("org")
c = lambda v: f"[{v[0]:.3f}, {v[1]:.3f}]"
L = ["# Summary of results (auto-generated by src/summarize.py)", "",
     "CIs are two-way (repos x make-up days) pairs bootstrap unless marked 'repo-only'.", ""]
e = R["E1"]
L += [f"## E1 (2023-01-15..2024-06-03): {e['repos_in_panel']} repos in panel, {e['eligible_repos']} eligible, {e['panel_days']} days with every hour covered",
      f"- make-up workdays used ({len(e['makeup_events'])}): {', '.join(e['makeup_events'])}"]
for k, g in e["groups"].items():
    L.append(f"- {k}: s={g['s']:.3f} {c(g['ci95_two_way'])} (repo-only {c(g['ci95'])}), n={g['repos']}, "
             f"placebo {g['placebo_mean']:+.3f}±{g['placebo_sd']:.3f}, z={g['z_vs_placebo']:.1f}")
L += [f"- per-repo BH q<0.05 with empirical placebo p (primary): {e['bh_emp_q05_repos']} repos; "
      f"{e['bh_emp_q05_repos_zh_lt_1pct']} with <1% Chinese titles; {e['bh_emp_q05_repos_zh_eq_0']} with none",
      f"- (normal-approximation p, anticonservative, for reference: {e['bh_q05_repos']} / {e['bh_q05_repos_zh_lt_1pct']})",
      "- holiday-dip mirror estimator by group: " + ", ".join(f"{k}={v:.3f}" for k, v in e["holiday_dip_by_group"].items()), ""]
pe = B["per_event"]
L += ["## Per-event uplift, repos with <1% Chinese titles: " + ", ".join(f"{k}: {v['zh<1%']:.3f}" for k, v in pe.items()),
      f"- positive on {sum(v['zh<1%'] > 0 for v in pe.values())} of {len(pe)} days", ""]
sh = X["split_half_2023_to_2024"]
L += ["## Split-half holdout: flagged on the 2023 make-up days -> measured on the 2024 make-up days",
      f"- flag rule: {sh['flag_rule']}",
      f"- flagged 2023: {sh['flagged_2023']} -> 2024 s={sh['flagged_2023_s_in_2024']:.3f} {c(sh['ci95'])}",
      f"- of which <1% Chinese titles: {sh['flagged_2023_zh_lt_1pct']} -> 2024 s={sh['hidden_s_in_2024']:.3f} {c(sh['hidden_ci95'])}",
      f"- not flagged -> 2024 s={sh['not_flagged_s_in_2024']:.3f} {c(sh['not_flagged_ci95'])}", ""]
h = R["holdout_E1_to_E2"]
L += ["## E1 -> E2 holdout (SIGN ONLY: E2 capture is degraded and has 4 make-up days; magnitudes not comparable)"]
for k in [k for k in h if k.startswith("E1 ")]:
    g = h[k]
    L.append(f"- {k}: n={g['repos']}; E2 sign {'positive' if g['E2_s'] > 0 else 'negative/zero'}, z vs E2 placebo = {g['E2_z_vs_placebo']:.1f}")
L += [""]
e2 = R["E2"]
L += ["## E2 (2025-10-16..2026-07-01): uninformative, sign only",
      f"- make-up days: {', '.join(e2['makeup_events'])}"]
for k in ("zh<1%", "zh>=1%"):
    g = e2["groups"][k]
    L.append(f"- {k}: two-way CI {c(g['ci95_two_way'])}, placebo sd {g['placebo_sd']:.3f}, z={g['z_vs_placebo']:.1f}")
L += [""]
L += ["## Holiday proximity"]
nd = B["near_date_placebo"]; L.append(f"- near-date placebo ({len(nd['days'])} ordinary same-weekday days 7-21 days from events): <1% s={nd['zh<1%']['s']:.3f} (z {nd['zh<1%']['z']}), >=1% s={nd['zh>=1%']['s']:.3f}")
pd_ = B["partner_day_DiD_common_set"]
for k in ("zh<1%", "zh=0", "zh>=1%"):
    g = pd_[k]; L.append(f"- partner-day DiD ({len(pd_['pairs'])} weekends, same repos), {k}: make-up {g['makeup_days_of_these_weekends']:.3f}, partner {g['partner_days']:.3f}, DiD {g['DiD']:.3f}")
pp = H["partner_days_hour_of_day_CST"]["zh<1%"]
L.append(f"- partner-day excess for <1% repos: {pp['excess_inside_09_19_CST']:.0f} actor-hours inside 09-19 CST vs {pp['excess_outside_09_19_CST']:.0f} outside")
L += [""]
L += ["## Mechanism: hour of day (Asia/Shanghai), E1"]
for k, g in H["hour_of_day_CST"].items():
    ex = g["excess_by_hour_CST"]
    L.append(f"- {k}: {g['excess_share_09_19_CST']:.1%} of make-up-day excess in 09-19 CST vs {g['gap_share_09_19_CST']:.1%} of the normal weekday gap; "
             f"s inside {g['s_inside_09_19']:.3f} vs outside {g['s_outside_09_19']:.3f}; excess 11h/12h/13h/14h = {ex[11]:.0f}/{ex[12]:.0f}/{ex[13]:.0f}/{ex[14]:.0f}")
u = H["utc_day_boundary"]
L += ["", f"## Day boundary: UTC days instead of Asia/Shanghai: <1% s={u['zh<1%']['s']:.3f} (placebo sd {u['zh<1%']['placebo_sd']:.3f}); >=1% s={u['zh>=1%']['s']:.3f}", ""]
L += ["## Same-time-zone controls (lower-threshold panel, E1; repo-only CIs)"]
for k, g in B["same_timezone_controls"].items():
    if g["repos"]:
        L.append(f"- {k}: s={g['s']:.3f} {c(g['ci95'])}, n={g['repos']}, placebo {g['placebo_mean']:+.3f}±{g['placebo_sd']:.3f}")
L += ["", "## GH Archive capture diagnostics (GitHub-wide human work events)",
      "- weekday events per day, E2 vs E1: " + ", ".join(f"{k} {v:+.0%}" for k, v in C["E2_over_E1_weekday_events_by_type"].items()),
      f"- hour-of-week CV: E1 {C['E1']['hour_of_week_cv']:.3f}, E2 {C['E2']['hour_of_week_cv']:.3f}; max/min {C['E1']['hour_of_week_max_over_min']:.2f} -> {C['E2']['hour_of_week_max_over_min']:.2f}",
      f"- weekend/weekday events: E1 {C['E1']['weekend_over_weekday_all']:.2f}, E2 {C['E2']['weekend_over_weekday_all']:.2f}",
      f"- opened-PR events with empty title: E1 {C['E1']['pr_opened_empty_title_share']:.0%}, E2 {C['E2']['pr_opened_empty_title_share']:.0%}",
      f"- within E2, non-push events Feb -> Jun 2026: {_np('2026-06') / _np('2026-02') - 1:+.0%}; push events: {C['monthly_events_by_type']['2026-06']['PushEvent'] / C['monthly_events_by_type']['2026-02']['PushEvent'] - 1:+.0%}", ""]
L += ["## Organisations, E1 only (two-way CI; median repo; pooled s without the org's 5 most influential repos)"]
for org in o1.index:
    r1 = o1.loc[org]
    L.append(f"- {org}: s={r1.s:.3f} [{r1.ci95_lo:.3f}, {r1.ci95_hi:.3f}] (n={int(r1.repos)}, Chinese-title share {r1.zh_title_share:.4f}); "
             f"median repo {r1.median_repo_s:.3f}; without top-5 {r1.s_without_top5:.3f}")
full = pd.read_csv(os.path.join(RES, "orgs_E1.csv")).set_index("org")
L.append(f"- apache: top-10 repos supply {full.loc['apache', 'top10_share_of_numerator']:.0%} of the pooled numerator")
open(os.path.join(RES, "SUMMARY.md"), "w").write("\n".join(L) + "\n")
print("\n".join(L))
